name: Main Build
on:  
    push:
        branches: ["master"]
    pull_request:
        branches: ["master"]        
    workflow_dispatch:

concurrency: 
  group: release-${{github.repository}}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      
    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
    - name: Setup JFrog CLI
      uses: jfrog/setup-jfrog-cli@v3
      env:
        JF_ENV_1: ${{  secrets.JF_URL }}
        
    - name: Ping JFrog CLI
      run: jf rt ping

       
    - name: Build & Publish
      env:
        REPO_NAME : libs-snapshot-local
      run: | 
        jf mvnc --repo-resolve-releases $REPO_NAME --repo-resolve-snapshots $REPO_NAME --repo-deploy-releases $REPO_NAME --repo-deploy-snapshots $REPO_NAME
        jf mvn clean install
        # Collect environment variables for the build
        jf rt bce
        # Collect VCS details from git and add them to the build
        jf rt bag
        # Publish build info
        jf rt bp     
        
   
    - name: Xray scan
      run: |
        jf bs --fail=false
     
