name: Main Build
on:  
    push:
        branches: ["master"]
    pull_request:
        branches: ["master"]        
    workflow_dispatch:

concurrency: 
  group: release-${{github.repository}}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    
      - uses: actions/checkout@v2     
      
      - uses: actions/cache@v1
        with:
            path: ~/.m2/repository
            key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
            restore-keys: |
                ${{ runner.os }}-maven-
                
      - name: Set up JDK 8
        uses: actions/setup-java@v2
        with:
          java-version: '8'
          distribution: 'adopt'
          overwrite-settings: false
      - name: Setup JFrog CLI
        # Install CLI 
        uses: jfrog/setup-jfrog-cli@v3
        env:
            # JFrog platform url (for example: https://acme.jfrog.io) 
            JF_URL: ${{ secrets.JF_URL }}

            # Basic authentication credentials
            JF_USER: ${{ secrets.JF_USER }}
            JF_PASSWORD: ${{ secrets.JF_PASSWORD }}
            # JFrog Platform access token
            JF_ACCESS_TOKEN: ${{ secrets.JF_ACCESS_TOKEN }}
       
    # JFrog Ping 
      - name: Ping JFrog CLI 
        run: |         
           jf rt ping
      - name: Deploy to PROD
        run: mvn deploy
