name: Java CI with Maven

on:
   push:
      branches: [ "master" ]
   pull_request:
      branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 8
        uses: actions/setup-java@v2
        with:
          java-version: '8'
          distribution: 'adopt'
          overwrite-settings: false
          
      - name: maven-settings-xml-action
        uses: whelk-io/maven-settings-xml-action@v20
        with:
             repositories: >
                [
                  {
                  "id": "snapshots",
                  "name": "a0hc1naqaua6m-artifactory-primary-0-snapshots",
                  "url": "https://sirahurajesh.jfrog.io/artifactory/libs-snapshot"
                  }       
                ]
           
             servers: >
                    [
                      {
                        "id": "central",
                        "username": "rajeshlawrance@gmail.com",
                        "password": "cmVmdGtuOjAxOjE3MDg1OTY5NDc6S2R3Mm16TlM5cnJPUHdYYXc2YThlQTNEMUFR"
                      }
                    ]
      - name: Build with Maven
        env:
          ARTIFACTORY_USERNAME_REF: "stream-github-actions"
          ARTIFACTORY_TOKEN_REF: "cmVmdGtuOjAxOjE3MDg1OTY5NDc6S2R3Mm16TlM5cnJPUHdYYXc2YThlQTNEMUFR"
          BUILD_ENV: 'github-actions'
        run: mvn -B package --file pom.xml

  release:
    runs-on: ubuntu-latest
    needs: build
    if: github.ref == 'refs/heads/master'

    steps:
        - name: Deploy
          uses: peaceiris/actions-gh-pages@v3
          with:
            github_token: ${{ secrets.GITHUB_TOKEN }}
            publish_dir: "https://sirahurajesh.jfrog.io/artifactory/libs-snapshot"
